services:
  db:
    container_name: postgres-hrm
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres-hrm
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5440:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres: